# Generated by Django 5.0.6 on 2024-06-20 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=255)),
                ('position', models.CharField(max_length=255)),
                ('resume', models.FileField(upload_to='resumes/')),
                ('additional_info', models.TextField()),
            ],
        ),
    ]
