# Generated by Django 5.0.6 on 2024-05-21 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('company_name', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('opened', 'Opened'), ('closed', 'Closed')], max_length=10)),
                ('years_of_exp', models.IntegerField()),
                ('description', models.TextField()),
            ],
        ),
    ]
