# Generated by Django 5.0.6 on 2024-05-21 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addnewjop', '0002_alter_job_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='status',
            field=models.BooleanField(),
        ),
    ]
