# Generated by Django 5.0.6 on 2024-05-21 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addnewjop', '0003_alter_job_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='status',
        ),
        migrations.AddField(
            model_name='job',
            name='is_opened',
            field=models.BooleanField(default=True),
        ),
    ]
