# Generated by Django 5.0.6 on 2024-05-21 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addnewjop', '0005_alter_job_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='id',
        ),
        migrations.AlterField(
            model_name='job',
            name='title',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
