# Generated by Django 5.0.6 on 2024-06-20 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addnewjop', '0006_remove_job_id_alter_job_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='apply',
            field=models.BooleanField(default=False),
        ),
    ]
